# permissions to do viewer demomicroservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demomicroservice-viewer-role
rules:
- apiGroups:
  - devops.my.domain
  resources:
  - demomicroservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devops.my.domain
  resources:
  - demomicroservices/status
  verbs:
  - get
