# permissions to do edit demomicroservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demomicroservice-editor-role
rules:
- apiGroups:
  - devops.my.domain
  resources:
  - demomicroservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.my.domain
  resources:
  - demomicroservices/status
  verbs:
  - get
  - patch
  - update
